genesis_id = "25f6e3b9295a61f69fcb956aca9f0076234ecf2e02d399db5448b6e22f26e81c"
dependencies = ["independent"]
system = "Sia"

[aliases]
coinmarketcap = "Siacoin"
CurrencyName = "siacoin"

[ratings]
rating_cyber = 2

[consensus]
consensus_name = "Proof-of-Work"
hashing = "Blake2b"
consensus_type = ""

[descriptions]
state = "Running"
tags = ["DAO"]
hashtag = "#siacoin"
system_type = "DAO"

[events]
announcement = "01/05/2014"

[token]
token_name = "siacoin"
token_symbol = "SC"

[specs]
block_time = 600
block_reward = "300000. Reward reduced by 1 every block intil reach 30000. After reamains constant"
supply = 4500000000

[[links]]
name = "Siacoin.com"
url = "http://siacoin.com/"
icon = "website.png"
tags = ["Main"]
type = "website"

[[links]]
name = "Nebulous organization on Github"
url = "https://github.com/NebulousLabs"
icon = "github.png"
tags = ["Main", "Code"]
type = "github"

[[links]]
name = "Sia Whitepaper"
url = "http://siacoin.com/sia.pdf"
icon = "whitepaper.png"
tags = ["Main", "Science"]
type = "paper"

[[links]]
name = "Explorer"
url = "http://explore.siacoin.com/"
icon = "explorer.png"
tags = ["Main", "Apps", "Analytics"]
type = "explorer"

[[links]]
name = "Twitter"
url = "https://twitter.com/NebulousLabs"
icon = "twitter.png"
tags = ["News"]
type = "twitter"

[[links]]
name = "Forum"
url = "https://forum.siacoin.com/"
icon = "forum.png"
tags = ["News"]
type = "forum"


[[links]]
name = "Slack"
url = "http://slackin.siacoin.com/"
icon = "slack.png"
tags = ["News"]
type = "slack"

[[links]]
name = "Facebook"
url = "https://www.facebook.com/nebulouslabs"
icon = "forum.png"
tags = ["News"]
type = "forum"

[[links]]
name = "Poloniex"
headline = "nein"
url = "https://www.poloniex.com"
type = "custom"
icon = "poloniex.png"
tags = ["Apps","Exchange"]
